### ISSUE TITLE
Check for unicode symbols that have to be written LaTeX

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#22]
This is an enhancement of #21 (check for unicode hypens and bullets in lists).

-  unicode arrows that have to been written LaTeX, e.g. U+2195 (arrow up and down) has to be in LaTeX \updownarrow.  Possible arrows: 2190—21FF 
- unicode capitel greek letter: 0391 - 03A9
- unicode small greek letter: 03B1- 03C8
- dieresis(wrong dots above a umlaut), the umlaut is shown correct for normal sighted reader, but the screen reader read this wrong and the braille display also shown it no correct.

Maybe it is helpful to have an adoptable catalog of symbols that have to be written in LaTeX

**Comment by humenda** [comment]
These are multiple issues indeed. 

1.  Checking for arrows isn't hard, I'll create an issue for that.
2.  Why exactly do you wish to check for greek letters only? These are mathematical signs, the Mistkerl will allert the editor automatically, when unicode is used within a maths environment. Outside that, I'm afraid that is not pratical: the list of possible mathematical characters is pretty large and a checker would need to know them all.
3.  An example for the dieresis, that you are talking about, would be great. There are many variations and in case of PDFs created by LaTeX and translated to plain text, this not only depends on the language, but also on the used font.

**Comment by humenda** [comment]
Not relevant anymore, GladTeX is able to cope with non-ascii characters like umlauts in formulas with the -R switch.
