### ISSUE TITLE
add conversion profiles

### ISSUE THREAD

**Issue by humenda** [TUD-INF-IAI-MCI/AGSBS-infrastructure#24]
Add a configuration option to specify conversion profiles. These could be used
to e.g. use MathJs instead of GladTeX, to make material more accessible for
visually impaired people and a default GladTeX profile which would be more
suitable for blind users.
The specification of the profile should NOT happen in the configuration, but is
a generation property, so for matuc, that would be an additional switch to conv
and master. There should be an option to query for available profiles and
internally, profiles should be an enum type, which can be easily converted to
and from string and raises an exception otherwise.

**Comment by jevo** [comment]
Maybe, it is also helpful to have a profile for proof readers.
So that more information are shown in the html-file and it is not necessary to check or read the Markdown file.

**Comment by humenda** [comment]
A concrete example would be good. I cannot see any useful use case. Despite it
would be a challenge to map the input source (markdown) into the resulting HTML.
The conversion is done by Pandoc and beyond our control; layout and conversion
are subject to changes.

**Comment by humenda** [comment]
closed by b03747a33f3a064a
