### ISSUE TITLE
Generation of Toc does not support line breaks

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#40]
The following example does not generate a correct toc entry:
```
# Grundorientierung 1:\
  Tiefenpsychologie / Psychoanalyse
```

Pandoc generates the correct HTML-Code:
```
<h1 id="grundorientierung-1-tiefenpsychologie-psychoanalyse">Grundorientierung 1:<br />
Tiefenpsychologie / Psychoanalyse</h1>
```

the generate inhalt.md contains the following line

`[3. Grundorientierung 1:\](k03/k03.html#grundorientierung-1)\`

The issue is caused by the backslash before the ] in the Markdown link syntax.

**Comment by humenda** [comment]
Hi

This is a bug in the heading parser. I'll have a look

Thanks
