### ISSUE TITLE
Adding page numbers uses german as default language

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#43]
The command 

`matuc addpnum -f k01.md 12`

 returns 

`pagenumber:  || - Seite 1 -`

the set language (<dc:language>) in the .lecture_meta_data.dcxml is not checked.

**Comment by humenda** [comment]
Hi

>The command 
>
>`matuc addpnum -f k01.md 12`
[…]

I would very much prefer a gradual adaption: take one module of MAGSBS, make it
use gettext, think of a useful abstraction to make it useable by the whole
package and make a PR. Once approved, we can do the rest.

The only question is: who does it? :)

**Comment by humenda** [comment]
I cannot reproduce this with latest master.
