### ISSUE TITLE
matuc imgdsc: does not check if the path exists

### ISSUE THREAD

**Issue by xplhak** [TUD-INF-IAI-MCI/AGSBS-infrastructure#45]
imgdsc path is not checked and the description is generated even if the picture does not exist.

May be this is a "feature" but more expected answer is something like "image file does not exist".

**Comment by humenda** [comment]
This is indeed a feature. `matuc imgdsc` was introduced to support Atom; it
allows to have the outsourcing logic all in one place. Matuc cannot know at
which stage this function is called and therefore it doesn't check for the image
path.

If you think this is worth-while supporting, please explain a concrete use case
where you think this is the wrong behaviour.

**Comment by xplhak** [comment]
We went through some use cases with Jens and you are right. PATH is checked in Atom and, therefore, there is no need to check it in matuc.
