### ISSUE TITLE
macOS Error when running `matuc conv k01.md`

### ISSUE THREAD

**Issue by polizoto** [TUD-INF-IAI-MCI/AGSBS-infrastructure#48]
When using the CLI on macOS, I encountered an error when attempting to convert a MarkDown file in my project folder.  I ran the following command:

`matuc conv k01.md`

And I received the following error:

>message:
>    TypeError: list indices must be integers or slices, not str

I then ran:

`export DEBUG=1`

And I followed this with the command 

`matuc conv k01.md`

This command produced the following output:

> error:
>  traceback:
>    Traceback (most recent call last):
>      File "/usr/local/lib/python3.6/site-packages/matuc_impl/__init__.py", line 330, in handle_conv
>        p.convert_files((args.file,))
>      File "/usr/local/lib/python3.6/site-packages/MAGSBS/pandoc/converter.py", line 128, in >convert_files
>        self.__convert_document(file_name, cache, converter, conf)
>      File "/usr/local/lib/python3.6/site-packages/MAGSBS/pandoc/converter.py", line 168, in >__convert_document
>        contentfilter.get_title(json_ast), path)
>      File "/usr/local/lib/python3.6/site-packages/MAGSBS/pandoc/contentfilter.py", line 148, in get_title
>        nodes_to_visit = json_ast['blocks'] # content of document without meta information
>    TypeError: list indices must be integers or slices, not str
>    
>  message:
>    TypeError: list indices must be integers or slices, not str

I am using a brew installation of Pandoc via the following command:

`brew install pandoc`

I have pandoc 2.1.1 installed.

**Comment by jevo** [comment]
See #49 maybe a downgrade to version 3.5.4 is the solution. 
After the installation of version 3.5.4 you have install the pandocfilters again

`pip3 install pandocfilters`

Because the module is stored in the path /usr/local/lib/**python3.5**/site-packages.

**Comment by polizoto** [comment]
I have pandoc-crossref installed via brew:

`brew install pandoc-crossref`

Are these the same filters as `pip3 install pandocfilters`

**Comment by polizoto** [comment]
I installed Python 3.54 and am receiving the same error when running the following command:

`matuc conv k01.md`

I receive the following error:

`error:
  message:
    TypeError: list indices must be integers or slices, not str`

and the debug report shows the following output:

`error:
  traceback:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matuc_impl/__init__.py", line 330, in handle_conv
        p.convert_files((args.file,))
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MAGSBS/pandoc/converter.py", line 128, in convert_files
        self.__convert_document(file_name, cache, converter, conf)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MAGSBS/pandoc/converter.py", line 168, in __convert_document
        contentfilter.get_title(json_ast), path)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/MAGSBS/pandoc/contentfilter.py", line 148, in get_title
        nodes_to_visit = json_ast['blocks'] # content of document without meta information
    TypeError: list indices must be integers or slices, not str
    
  message:
    TypeError: list indices must be integers or slices, not str
`

**Comment by polizoto** [comment]
I was running an older version of pandoc after all (1.12.4.2 ) and calling it from 

/usr/local/bin/pandoc

and not from my brew installation

/usr/local/Cellar/pandoc

where I have v 2.1.1 installed.

All is good now. I was able to run

`matuc conv k01.md`

without any problems.
