### ISSUE TITLE
Replace all in code defined message for  internationalization 

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#51]
For the internationalization all messages for warnings/errors etc. have to be replaced by gettext.
In the following listing all fix defined messages are listed with filenames(line number) followed by the message type :

- [ ] master.py (67) - NoLectureConfigurationError
- [ ] config.py (222) - ConfigurationError

**Comment by humenda** [comment]
This is a duplicate of #42, please comment there.
Thanks
