### ISSUE TITLE
Extension of markdown checker

### ISSUE THREAD

**Issue by xplhak** [TUD-INF-IAI-MCI/AGSBS-infrastructure#61]
During implementation of linkchecker, which needs to have correct links, I thought about following markdown structure test. We can discuss, which should be implemented.

class TitleInLinkCannotContainFormatting():
    """ When using INLINE_LINK_WITH_TITLE, it is not allowed to have formatting information within link title. """

class TitleIsTooLong():
    """ Title should be 'reasonably' long. Long text lowers the readability and they also can be caused by a incorrect syntax of link. """

class TitleInInlineLinkIsCorrect():
    """check if it is correctly build using " or ' (the last char should be the there at least twice - and first one is the end of the link """

class NoSpaceBetweenRoundAndSquareBrackets():
    """ When the inline link or labeled link is used, it is not allowed by
    pandoc to have a space/spaces between square and round brackets."""

**Comment by humenda** [comment]
I think you should replace Title through Text or LinkText, to make it more
obvious.

>class TitleInLinkCannotContainFormatting():
>    """ When using INLINE_LINK_WITH_TITLE, it is not allowed to have formatting information within link title. """
`[foo *bar*](baz)` is legal, or do you mean something else?

>class TitleIsTooLong():
+1
>class TitleInInlineLinkIsCorrect():
Not sure what this one is good for, maybe an example could clarify this.

>class NoSpaceBetweenRoundAndSquareBrackets():
Isn't a link first made of the bracket, then of the prenthesis?
There's a checker called "BrokenImageLinksAreDetected", but it has potentially
the wrong name, since it checks for both images and links, just extend this one,
I'd say.

**Comment by xplhak** [comment]
>>I think you should replace Title through Text or LinkText, to make it more
>>obvious.

Agree.

>class TitleInLinkCannotContainFormatting():
>   """ When using INLINE_LINK_WITH_TITLE, it is not allowed to have formatting information within link > title. """
>> `[foo *bar*](baz)` is legal, or do you mean something else?

From the pandoc documentation: There can be no space between the bracketed part and the parenthesized part. The link text can contain formatting (such as emphasis), but the title cannot.
E.g. [foo][link "title *bold* fail" is not allowed.

> class TitleInInlineLinkIsCorrect():
>>Not sure what this one is good for, maybe an example could clarify this.

From my point of view, problems like [foo](bar "title') could be detected. Note: first char is ", the second is '

> class NoSpaceBetweenRoundAndSquareBrackets():
>Isn't a link first made of the bracket, then of the prenthesis?
>>There's a checker called "BrokenImageLinksAreDetected", but it has potentially
>>the wrong name, since it checks for both images and links, just extend this one,
>>I'd say.

Ok, this checker could be useful (and its extension should be enough). However, links are not only inline, but there can be also labeled one. E.g. Text text text [mylink][ref], with a reference. [ref]: link

**Comment by humenda** [comment]
>>>I think you should replace Title through Text or LinkText, to make it more
>>>obvious.
>
>Agree.
Ok my bad, I didn't know about the title extension of Pandoc. For the time
being, I would ignore it. The title attribute is not really useful for
accessible books or slides and if we should ever hit this edge case, it is not
worth writing code for it. Just ignore titles all together.

>From the pandoc documentation: There can be no space between the bracketed part and the parenthesized part. The link text can contain formatting (such as emphasis), but the title cannot.
>E.g. [foo][link "title *bold* fail" is not allowed.
Ok, so please refine the checker I mentioned above and we are done :).

Thanks

**Comment by humenda** [comment]
Could you please summarise what is left to finish this task?

**Comment by xplhak** [comment]
I think this issue can be closed, as we ignore titles and NoSpaceBetweenRoundAndSquareBrackets can cause many false possitives.
