### ISSUE TITLE
Support ePUB output format

### ISSUE THREAD

**Issue by SushiTee** [TUD-INF-IAI-MCI/AGSBS-infrastructure#79]
ePUB: https://de.wikipedia.org/wiki/EPUB

Matuc should support converting to ePUB

**Comment by SushiTee** [comment]
Little status update:

I added a content filter which replaces the page numbers with the following html:

```
<p class="pagebreak"><span id="p{0}">{1}</span></p>
```

In combination with the following css it does a page break:

```
p.pagebreak { page-break-before: always; }
h1 + p.pagebreak { page-break-before: avoid; } /* prevents page break if h1 is before the page number*/
```

It does work in Microsoft Edge. It does not work in Readium.

**Comment by humenda** [comment]
Looks good to me, though I didn't test it.

**Comment by SushiTee** [comment]
I'ce got an idea to exclude images from the toc. It should be possible to change the headline from __h1__ to something else and let it look like a headline via css. Is this an option?

**Comment by humenda** [comment]
Hi

Even better would be to not use headings at all, that's something introduced by
@jevo. An anchor should be enough, e.g.

k01.md:

```
[![image description outsourced](blah.png)](bilder.html#blah)
```

bilder.md:

```
<span id="blah">Image description of Blah</span>
Desc desc desc.
```

**Comment by SushiTee** [comment]
With the last change all image descriptions are moved to the end of the last chapter. It might be a good idea to create a chapter only for image descriptions but for all images and not per chapter.

The headline tags (h1, h2, ...) are replaced by a simple paragraph.

Before:

```
<section id="description" class="level1">
<h1>Description</h1>
<section id="image-of-blub" class="level2">
<h2>Image of Blub</h2>
```

After:

```
<p id="description" class="header pagebreak" data-level="1">Description</p>
<p id="image-of-blub" class="header" data-level="2">Image of Blub</p>
```

for level 1 header a page break is done. The class __header__ and __data-level__ is just for visual purpose so it actually looks like a headline.

Also the tocDepth from the lecture meta data should now work as intendet. The __.md__ file which might contain the toc is simply ignored as pandoc generates it's own toc for epub.

**Comment by SushiTee** [comment]
8fbbea6 makes images show correctly (links to description are not working yet). Also formulas work.

Pandoc scans the AST for images and automatically copies them to EPUBnif it finds the images.
Due to the structure of many markdown files within different subdirectories it does not work without a content filter. All Image URLs must be relative to the pandoc _resource path_ (see pandoc's --resource-path).

**Comment by SushiTee** [comment]
359096a makes relative links in epub work. It may happen that the same "id" is used more than once due to the way the image id generation works.  The id's of images should be unique in the markdown structure already.
I suggest something like: _<chapter number>_<image count>_<old id>_

For example:

Before

```
[![Bildbeschreibung ausgelagert](bilder/image5.jpeg)](bilder#foto-of-something)
```

After

```
[![Bildbeschreibung ausgelagert](bilder/image5.jpeg)](bilder.md#k03_5_foto-of-something)
```

This says that the image is in chapter 3 and it is foto number 5. This makes it possible to have unique id's even though the same name of an image is used twice within one chapter.
Also it should work for epub which automatically generates the chapters and is completely independent of the markdown structure.

**Comment by humenda** [comment]
>I suggest something like: _<chapter number>_<image count>_<old id>_
We discussed this earlier, please use `chxx_OLDID` or alike.

Yes, the image descriptions should all be in one place, be it a chapter or
something else. Preferably, EPUB would have the possibility to append text
*after* the chapters, e.g. a backmatter. Have you investigated this?

**Comment by jevo** [comment]
Please also use a epub checker like https://github.com/paginagmbh/EPUB-Checker for checking the generated epub...

**Comment by SushiTee** [comment]
> We discussed this earlier, please use `chxx_OLDID` or alike.
it should not be done by a filter but should be already like this when the markdown is created. E.g. when generating it from powerpoint.

> Yes, the image descriptions should all be in one place, be it a chapter or something else. Preferably, EPUB would have the possibility to append text *after* the chapters, e.g. a backmatter. Have you investigated this?
I looked for it but I didn't find anything yet.

**Comment by humenda** [comment]
>> We discussed this earlier, please use `chxx_OLDID` or alike.
>it should not be done by a filter but should be already like this when the
>markdown is created. E.g. when generating it from powerpoint.
It should be done by the output format, because Markdown is written by hand. The
case that you are referring to is one particular case where PowerPoint slides
are imported into markdown, the majority is edited more less manually by hand
from PDF, LaTeX and other sources. We cannot burden the lecture editor to always
use unique labels, especially if multiple persons are working on one
lecture/material. Additionally, this is a special requirement of EPUB and hence
should be handled as such.

**Comment by SushiTee** [comment]
d350d5a9fc2fa60785784dc7c7c1373cbf46e011 changes each header ID. The chapter is used as prefix (_k01_, _k02_, ...). For images _image__ is prepended additionally.
Linking to images work as long as there are no cross chapter links.

**Comment by SushiTee** [comment]
fe5a6f0 adds some meta data to epub.

A yaml template is used for this. The values form MetaInfo are put in it. A special AST is generated for the meta data which is appended to the complete AST

**Comment by SushiTee** [comment]
> Please also use a epub checker like https://github.com/paginagmbh/EPUB-Checker for checking the generated epub...

I checked the generated epub. The epub is without any problems. At least the conversion works well. All the errors in it you may have found in the eboub I sent you are errors from the markdown structure I used to generate it except for one error which is an error of gladtex.

The file extension of the images are _.jpg_ even though they are _.png_

For gladtex I already created an [issue](https://github.com/humenda/GladTeX/issues/8) with a suggestion on how to fix it.

**Comment by humenda** [comment]
Thanks for your work. After the 0.8 release cycle, this has been finally merged. This is a very helpful stepping stone.
