### ISSUE TITLE
Update links for output formats

### ISSUE THREAD

**Issue by humenda** [TUD-INF-IAI-MCI/AGSBS-infrastructure#82]
At the moment, editors of our MarkDown are forced to create links with a correct file suffix, e.g. `[foo](bar.html)`. Ideally, each output format would have a contentfilter to transform links to MarkDown files to the appropriate link format in the output format, e.g.:

Link: `[text](reference.md)`
HTML: `[text](reference.html)`
EPUB: `[text](ch01.notsure)`

These need to correctly map our source structure to the structure of the output format. For HTML, it's just replacing the file extension, EPUB material is completely rearranged.

This issue is part of #79 and should be worked on before #79 is closed.

**Comment by SushiTee** [comment]
change 0a32850 makes it work for html. All relative links are converted from _.whatever_ (e.g. _.md_) to _.hmtl_. For html it only makes sense to use _.html_ so it doesn't matter what the extension in the markdown file is. It is even possible to make the link without any extension in the makrdown file:

```
[text](reference)
```

**Comment by SushiTee** [comment]
The last change should fix this issue.

There is a problem if the anchor id's are not unique but I think this is a problem of the markdown.

**Comment by humenda** [comment]
>There is a problem if the anchor id's are not unique but I think this is a problem of the markdown.
Depends. It might be worth discussing whether all labels should be prefixed with
a chapter-specific prefix to avoid confusion. I'm not sure about the
consequences at the moment.
